export const btnContainer = [
  { name: "Clicker 3D", type: "Click", skill: "CSS", text: true, title: true },
  { name: "SkewBG", type: "Hover", skill: "CSS", text: true, title: true },
  { name: "Wavey", type: "Click", skill: "CSS", text: true, title: true },
  {
    name: "Gooey",
    type: "Hover",
    skill: "SVG Filter",
    text: false,
    posCenter: true,
    title: false,
  },
  {
    name: "Move Behind",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: true,
    title: false,
  },
  {
    name: "CircleArrow",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Blur Text",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  ,
  {
    name: "Layered",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Bubble",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: true,
    title: false,
  },
  {
    name: "Wave Brick",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Ripple",
    type: "Hover",
    skill: "SVG Filter",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Vertical Brick",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Neon",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Moving Bot",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Popping Circle",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
];
