export const btnContainer = [
  {
    name: "Clicker 3D",
    type: "Click",
    skill: "CSS",
    text: true,
    title: true,
  },
  { name: "SkewBG", type: "Hover", skill: "CSS", text: true, title: true },
  {
    name: "Gooey",
    type: "Hover",
    skill: "SVG Filter",
    text: false,
    posCenter: true,
    title: false,
  },
  {
    name: "Highlight Pen",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  { name: "Wavey", type: "Hover", skill: "CSS", text: true, title: true },
  {
    name: "Move Behind",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: true,
    title: false,
  },
  {
    name: "CircleArrow",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Layered",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Wave Brick",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Wi-de",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Bubble",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Ripple",
    type: "Hover",
    skill: "SVG Filter",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Vertical Brick",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Neon",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Moving Bot",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Popping Circle",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Hover 3D",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Shining Window",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Shutter",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "NuneTine",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Diamond",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Pung",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Updown Updown",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Curtain",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Overlap",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "KungDuck",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Spinning Border",
    type: "Hover",
    skill: "SVG",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "MasterCircle",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Yeahhhh",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Noooope",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Trees",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Shake Your Head",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Shake Your Belly",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Corner Up",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Puding",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Draw Line",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Overlay Line",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Speech Bubble",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "BG_O",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "BG_X",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Double Window",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Draw Circle",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Ctrl A",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Ctrl C",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Ctrl V",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Detect Click",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Detect Enter",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "BG Stripe",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "MakeFrame",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "MovieCut",
    type: "Hover&Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "PopChange",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "FullScreen",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Receipt",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "DragBox",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "AddAndDelete",
    type: "Hover&Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Button Window",
    modal: "Modal",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Stretch Window",
    modal: "Modal",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Slide Text",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "PopYesNo",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "FlyAway",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Net",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "RollingOX",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "ABSlide",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Checklist",
    type: "Select",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "BubbleCheck",
    type: "Select",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Indicating Arrow",
    type: "Select",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "TodoList",
    type: "Select",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Following Cursor",
    type: "Select",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "BG Right",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "RollingDia",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "BGChange Button",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Gathering",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Make Distance",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "zaranara",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Box Check",
    type: "Select",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "CheckToX",
    type: "Select",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "SwitchCircle",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Move Namecard",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Pop Namecard",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Falldown Namecard",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Rumbling Box",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Reverse Card",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "CoverUp",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Vibration",
    type: "Motion",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "DDoingDDoing",
    type: "Motion",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Shield",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "DDiyong",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Spinning Angle",
    type: "Motion",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "TearTicket",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Long Shadow",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Shadow Particle",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "StepBotLine",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Machine",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Move Gradation",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "BorderColor Change",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Moon",
    duration: "Hold",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Expending Checker",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "FourBalls",
    type: "Motion",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Jiggle",
    type: "Motion",
    skill: "SVG",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "LoadingBalls",
    type: "Motion",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  // {
  //   name: "Raindrop",
  //   type: "Click",
  //   skill: "CSS",
  //   text: true,
  //   posCenter: false,
  //   title: false,
  // },
  // {
  //   name: "Blur Text",
  //   type: "Hover",
  //   skill: "CSS",
  //   text: true,
  //   posCenter: false,
  //   title: false,
  // },
];
