export const btnContainer = [
  {
    name: "Clicker 3D",
    duration: "Short",
    type: "Click",
    skill: "CSS",
    text: true,
    title: true,
  },
  { name: "SkewBG", type: "Hover", skill: "CSS", text: true, title: true },
  {
    name: "Gooey",
    type: "Hover",
    skill: "SVG Filter",
    text: false,
    posCenter: true,
    title: false,
  },
  {
    name: "Highlight Pen",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  { name: "Wavey", type: "Click", skill: "CSS", text: true, title: true },
  {
    name: "Move Behind",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: true,
    title: false,
  },
  {
    name: "CircleArrow",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Blur Text",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  ,
  {
    name: "Layered",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Wave Brick",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Wi-de",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Bubble",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Ripple",
    type: "Hover",
    skill: "SVG Filter",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Vertical Brick",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Neon",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Moving Bot",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Popping Circle",
    duration: "Long",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Hover 3D",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Shining Window",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Shutter",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "NuneTine",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Diamond",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Pung",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Updown Updown",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Curtain",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Overlap",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "KungDuck",
    duration: "Long",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Spinning Border",
    type: "Hover",
    skill: "SVG",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "MasterCircle",
    duration: "Long",
    type: "Click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Yeahhhh",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Noooope",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Trees",
    duration: "Long",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Shake Your Head",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Shake Your Belly",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Corner Up",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Puding",
    duration: "Long",
    type: "click",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Draw Line",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Overlay Line",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Speech Bubble",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "BG_O",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "BG_X",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Double Window",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Draw Circle",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: false,
  },
  {
    name: "Ctrl A",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Ctrl C",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Ctrl V",
    type: "Hover",
    skill: "CSS",
    text: true,
    posCenter: false,
    title: true,
  },
  {
    name: "Detect Click",
    type: "Click",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
  {
    name: "Detect Enter",
    type: "Hover",
    skill: "CSS",
    text: false,
    posCenter: false,
    title: false,
  },
];
